### ISSUE TITLE
Add a support of a kind of rule files for dependaboot.

### ISSUE THREAD

**Issue by fletort** [fletort/init-repo-action#54]
To can personalize Dependabot file easily on each template without writing a lot of jinja2 sentence, it will be great to can have an input "Dependabot rules files" that can personalize all items of the Dependabot file, except package-ecosystem and directory.

These rules could be defined for a specific package ecosystem, or for all (use if not defined for specific). For example, such YAML file could be used :
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    # Specify labels for npm pull requests
    labels:
      - "npm"
updates:
  - package-ecosystem: "npm"
    schedule:
      interval: "weekly"
    # Specify labels for all other pull requests
    labels:
      - "other"
```
This example will apply NPM label when it is a Dependabot related to NPM ecosystem, in other case it will apply the other label.

This file is used to build the final Dependabot file. The original Dependabot file of the template must define all mandatory fields: package-ecosystem, directory, schedule. The rule file can modify the schedule definition and add other optional input. It can **not** be used to change package-ecosystem or directory. package-ecosystem  is used to see which rule will be used for the current file, and directory value is internal to template organization.

Maybe a new action can be used for that, or at list a developed cli that will be call by this action.
